<!DOCTYPE html>
<html>
<head>
	<title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Admin Board</title>
</head>
<body>
<div class="footer">
    <div class="container" style="text-align: center;">
        <b class="copyright">&copy; 2017 Admin Board - EGrappler.com </b>All rights reserved.
    </div>
</div>
</body>

</html>